#   com.carlstahmer.com.estc.recordimport configuration file
#   use this file to set basic configurations.  Settings
#	can be overwritten at run-time, but application will not
#   start if this file is not present in the document root.

#   The directory where the daemon should look for files
listendir: /Users/cstahmer/Documents/estc_record_importer/MARCTESTS/read

#   The directory where the daemon should write data.  This is
#   the directory that the XC Marctools server is monitoring
writedir: /Users/cstahmer/Documents/estc_record_importer/MARCTESTS/write

#   The MARC organization code that will be used as the indentifier for
#   the owner/originator of the converted records
orgcode: curives

#   The interval that the daemon should wait between processes
runinterval: 5000

#	The SQL Server Name
dbserver: localhost

#	The SQL Databse
dbname: estcimports

#	The SQL User
dbuser: root

#	The SQL Password
dbpass: password